### ISSUE TITLE
Can't install APK

### ISSUE THREAD

**Issue by VirtualPedestrian** [EmiyaSyahriel/CrossLauncher#20]
My phone tells me the APK is corrupted

**Comment by EmiyaSyahriel** [comment]
I have added the signed release APK to the current release page [here](https://github.com/EmiyaSyahriel/CrossLauncher/releases/tag/alpha), check if you can install it, and if it is, you may close this issue. 

I forget if this keystore is the same as the last release since I just found a random keystore with a familiar name in my PC storage since I reorganised my directory long time ago and forget where I put the keystore file. In case it's different, it also will fail to update the existing app due to clashing signature.

**Comment by EmiyaSyahriel** [comment]
Hello, Is this issue still remains in the latest release? If it's resolved, then please close this issue. I'll close this issue if there is no feedback before **Feb 28, 2023**
