### ISSUE TITLE
Can you compress it into an APK file?

### ISSUE THREAD

**Issue by Szymon621** [EmiyaSyahriel/CrossLauncher#3]
Jednak nieistotne

**Comment by VirtualPedestrian** [comment]
Download it here https://github.com/EmiyaSyahriel/CrossLauncher/releases

**Comment by Szymon621** [comment]
Yes thank you, I have already found. Thank you for the best launcher I have
ever used. PlayStation 3 is my favorite console ever, so I enjoy using the
launcher inspired by it.  From what I saw help with the translation is
needed? I'm not sure, but if it's true - I can help with the Polish
language. I don't write much English, but Polish is another matter! Yes…

pt., 18 gru 2020, 14:14 użytkownik VirtualPedestrian <
notifications@github.com> napisał:

**Comment by EmiyaSyahriel** [comment]
So this issue is done then. And yes, We need translation for this project.

To translate the project, you can fork this repo, open it in Android Studio, open the Localization Editor / String Editor from there, add your language, then start translating. And when done, you can Commit, Push, and merge your repo to this repo.

Or if you cannot use Android Studio, just download [this file](https://github.com/EmiyaSyahriel/CrossLauncher/raw/master/app/src/main/res/values/strings.xml), make a copy of it, translate it while using the copy as your reference. Then send it [here](https://github.com/EmiyaSyahriel/CrossLauncher/discussions/categories/manual-translations). By the way, Issue page is for issues only, for APK request and other thing like resource submission. You can go to the [Discussion page](https://github.com/EmiyaSyahriel/CrossLauncher/discussions).

**And currently I am not very active because I have a project at work. So, There wouldn't be much update unless I have some free time.**
