### ISSUE TITLE
Option In Settings That Makes It So That Live Icons Only Display When Hovering Over The App

### ISSUE THREAD

**Issue by AkiraKusanagi** [EmiyaSyahriel/CrossLauncher#46]
On the PSP and PS3, the live icons did not display until you hovered over the app. In the launcher, the live icons display whenever they're in the field of view. It would be nice if there was an option added in the settings that makes it so that the live icons would only play when hovering over the app, not in the field of view.

**Comment by AkiraKusanagi** [comment]
Hoo! Long title.

**Comment by AkiraKusanagi** [comment]
Oh yeah, also, it would also be cool if you're able to set an interval before the live Icons start when you hover over them. Like for the PSP, it was like 1.5 seconds of hovering over the application before it's live icons started.

**Comment by EmiyaSyahriel** [comment]
As far as my memory goes, PS3 did play animated icon when it enters the screen, but the icon is played a bit later, either because of the slow read time of PS3 hard disk or it was intentional by the original XMB developer.

As for PSP, I never owned one, so I just copy the layout off YouTube videos (that unfortunately never shows any animated icon), but I think it make sense that it goes like what you described since PSP has limited hardware.

But sure, I'll implement it once I have the time.

**Comment by AkiraKusanagi** [comment]
Was implemented in an Action Build.
