### ISSUE TITLE
Switching Wi-Fi on while the apps are loading crashes the launcher

### ISSUE THREAD

**Issue by AkiraKusanagi** [EmiyaSyahriel/CrossLauncher#47]
While the spinning clock is spinning and the apps are loading, switching on the Wi-Fi makes some of the app's names go missing, show a loading icon, then a few seconds later, the launcher crashes.

**Comment by EmiyaSyahriel** [comment]
For some reason, I cannot reproduce this bug with the updated code right now due to faster app listing, That I cannot race against it to switch Wi-Fi before it's  ended. I'll try with the now released apk.

Some question :
- Is it only switching Wi-Fi on, or until it's connected?
- Do you use release apk or debug apk? 
    - If you are using debug apk, can you post the log file at `(Internal Storage)/Android/data/id.psw.vshlauncher/logs.txt` if it exists?

**Comment by EmiyaSyahriel** [comment]
Cannot fully reproduce the bug solely by given info, need more info.

**Comment by AkiraKusanagi** [comment]
Info:

-  The release version of the apk was used

- The device used was an HPPL60A
- Android version is 12

**Comment by AkiraKusanagi** [comment]
My bad. So sorry. I restarted the phone and tried to turn on the Wi-Fi while the apps were loading and there's no issue. 😰
